name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      - name: Install git and LFS
        run: |
          sudo apt update
          sudo apt install -y git git-lfs openssh-client
          git lfs install

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_PERSONAL_TOKEN }}
        run: |
          git config user.email "22CS01042@iitbbs.ac.in"
          git config user.name "Aswadham"
          git remote add hf https://Aswadham:${HF_TOKEN}@huggingface.co/spaces/Aswadham/llm
          git push -f hf main
