name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Install git
        run: apk update && apk add openssh-client git

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face hub
        run: |
          git config user.email "your-email@here"
          git config user.name "your-identifier"
          git push -f https://Aswadham:${HF_PERSONAL_TOKEN}@huggingface.co/spaces/Aswadham/llm main
